# Generated by Django 5.2.5 on 2025-09-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabr',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
