# Generated by Django 4.2.24 on 2025-09-16 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='dateFabr',
            field=models.DateField(default=datetime.date(2025, 9, 16)),
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('refProd', 'idRayon')},
        ),
    ]
